//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public ChamCong()
        {
            this.ctChamCong = new HashSet<ctChamCong>();
        }
    
        public string MaCC { get; set; }
        public string MoTa { get; set; }
        public double HeSo { get; set; }
    
        public virtual ICollection<ctChamCong> ctChamCong { get; set; }
    }
}
