//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctThuongPhat
    {
        public string MaNV { get; set; }
        public string MaThuongPhat { get; set; }
        public string MaThang { get; set; }
        public int NgayThuongPhat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Thang Thang { get; set; }
        public virtual ThuongPhat ThuongPhat { get; set; }
    }
}
