//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.ctBaoHiem = new HashSet<ctBaoHiem>();
            this.ctChamCong = new HashSet<ctChamCong>();
            this.ctPhuCap = new HashSet<ctPhuCap>();
            this.ctThuongPhat = new HashSet<ctThuongPhat>();
            this.HopDong = new HashSet<HopDong>();
            this.NghiPhep = new HashSet<NghiPhep>();
            this.NguoiPhuThuoc = new HashSet<NguoiPhuThuoc>();
            this.PhongBan = new HashSet<PhongBan>();
        }
    
        public string MaNV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string CCCD { get; set; }
        public string MaPB { get; set; }
        public string MaCV { get; set; }
        public string MaHD { get; set; }
    
        public virtual ICollection<ctBaoHiem> ctBaoHiem { get; set; }
        public virtual ICollection<ctChamCong> ctChamCong { get; set; }
        public virtual ICollection<ctPhuCap> ctPhuCap { get; set; }
        public virtual ICollection<ctThuongPhat> ctThuongPhat { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual ICollection<HopDong> HopDong { get; set; }
        public virtual HopDong HopDong1 { get; set; }
        public virtual ICollection<NghiPhep> NghiPhep { get; set; }
        public virtual ICollection<NguoiPhuThuoc> NguoiPhuThuoc { get; set; }
        public virtual ICollection<PhongBan> PhongBan { get; set; }
        public virtual PhongBan PhongBan1 { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
