//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public PhongBan()
        {
            this.NhanVien1 = new HashSet<NhanVien>();
            this.ThongBao = new HashSet<ThongBao>();
        }
    
        public string MaPB { get; set; }
        public string TenPB { get; set; }
        public string SDT { get; set; }
        public string MaTrP { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<NhanVien> NhanVien1 { get; set; }
        public virtual ICollection<ThongBao> ThongBao { get; set; }
    }
}
