//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuCap
    {
        public PhuCap()
        {
            this.ctPhuCap = new HashSet<ctPhuCap>();
        }
    
        public string MaPhuCap { get; set; }
        public string LoaiPhuCap { get; set; }
    
        public virtual ICollection<ctPhuCap> ctPhuCap { get; set; }
    }
}
