//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhanSuEntities : DbContext
    {
        public QuanLyNhanSuEntities()
            : base("name=QuanLyNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaoHiem> BaoHiem { get; set; }
        public DbSet<ctBaoHiem> ctBaoHiem { get; set; }
        public DbSet<ctChamCong> ctChamCong { get; set; }
        public DbSet<ctPhuCap> ctPhuCap { get; set; }
        public DbSet<ctThuongPhat> ctThuongPhat { get; set; }
        public DbSet<ChamCong> ChamCong { get; set; }
        public DbSet<ChucVu> ChucVu { get; set; }
        public DbSet<HopDong> HopDong { get; set; }
        public DbSet<LoaiTaiKhoan> LoaiTaiKhoan { get; set; }
        public DbSet<NghiPhep> NghiPhep { get; set; }
        public DbSet<NguoiPhuThuoc> NguoiPhuThuoc { get; set; }
        public DbSet<NhanVien> NhanVien { get; set; }
        public DbSet<PhongBan> PhongBan { get; set; }
        public DbSet<PhuCap> PhuCap { get; set; }
        public DbSet<TaiKhoan> TaiKhoan { get; set; }
        public DbSet<Thang> Thang { get; set; }
        public DbSet<ThongBao> ThongBao { get; set; }
        public DbSet<ThuongPhat> ThuongPhat { get; set; }
    }
}
