//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thang
    {
        public Thang()
        {
            this.ctChamCong = new HashSet<ctChamCong>();
            this.ctPhuCap = new HashSet<ctPhuCap>();
            this.ctThuongPhat = new HashSet<ctThuongPhat>();
            this.NghiPhep = new HashSet<NghiPhep>();
        }
    
        public string MaThang { get; set; }
        public string MoTa { get; set; }
        public int SoNgayCongChuan { get; set; }
    
        public virtual ICollection<ctChamCong> ctChamCong { get; set; }
        public virtual ICollection<ctPhuCap> ctPhuCap { get; set; }
        public virtual ICollection<ctThuongPhat> ctThuongPhat { get; set; }
        public virtual ICollection<NghiPhep> NghiPhep { get; set; }
    }
}
