//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_3Tang_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongPhat
    {
        public ThuongPhat()
        {
            this.ctThuongPhat = new HashSet<ctThuongPhat>();
        }
    
        public string MaThuongPhat { get; set; }
        public string Loai { get; set; }
        public int SoTien { get; set; }
        public string LyDo { get; set; }
    
        public virtual ICollection<ctThuongPhat> ctThuongPhat { get; set; }
    }
}
